name: isolates_feature
description: Isolates showcase module.
publish_to: none
environment:
  sdk: ^3.6.0
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  get_it:
  go_router:
  app_core:
    path: ../../packages/core
flutter:
  uses-material-design: true
