name: deep_linking_feature
description: Deep linking showcase module.
publish_to: none
environment:
  sdk: ^3.6.0
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  app_core:
    path: ../../packages/core
flutter:
  uses-material-design: true
