name: push_notifications
description: Push notifications feature module.
publish_to: none
environment:
  sdk: ^3.6.0
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  firebase_core:
  firebase_messaging:
  flutter_local_notifications:
  googleapis_auth:
  go_router:
  sample_latest:
    path: ../..
flutter:
  uses-material-design: true
