include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    directives_ordering: true

analyzer:
  errors:
    depend_on_referenced_packages: ignore
    deprecated_member_use: ignore
    file_names: ignore
    use_build_context_synchronously: ignore
