name: feature_discovery_module
description: Feature discovery overlays module.
publish_to: none
environment:
  sdk: ^3.6.0
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  feature_discovery:
    git:
      url: https://github.com/maheshmnj/feature_discovery.git
      ref: master
  shared_preferences:
  app_core:
    path: ../../packages/core
flutter:
  uses-material-design: true
