name: smart_control_iot
description: Smart control IoT feature module.
publish_to: none
environment:
  sdk: ^3.6.0
resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  get_it:
  fpdart:
  equatable:
  shelf:
  shelf_router:
  go_router:
  flutter_staggered_grid_view:
  app_core:
    path: ../../packages/core
flutter:
  uses-material-design: true
