name: Flutter End to End

on:
  push:
    branches: [ 30-ci-cd-piple-for-android-apk-using-github-actions ]  # Trigger on pushes to the main branch (adjust as needed)

jobs:
  build:
    runs-on: ubuntu-latest  # Replace with a suitable runner if needed

    steps:
      - uses: actions/checkout@v3  # Checkout your code from the repository

#      - name: Set up Java JDK
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11.0.12'  # Adjust if needed

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.19.1'  # Replace with your desired Flutter version

      - name: Get pub dependencies
        run: flutter pub get

#      - name: Analyze code
#        run: flutter analyze

      - name: Build APK
        run: flutter build apk --no-tree-shake-icons

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: flutter-apk
          path: build/app/outputs/apk/release/app-release.apk
